# Generated by Django 4.2.2 on 2023-08-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('hotel_name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('video', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('review_text', models.TextField(null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=100, null=True)),
                ('password1', models.CharField(max_length=100, null=True)),
                ('email1', models.EmailField(max_length=254, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reply', models.TextField(null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelreview')),
            ],
        ),
    ]
